runtime: nodejs20
service: cldmgt-supporttool-client

handlers:
  # Serve static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/.*\..+$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

# handlers:
#   - url: /static
#     static_dir: dist/static

#   - url: /(.*)
#     static_files: dist/index.html
#     upload: dist/index.html

#   - url: /.*
#     script: auto